---
title: "1. Build a model"
output: html_notebook
---


```{r}
#install.packages("tidymodels")
library(tidymodels)
library(readr)
library(broom.mixed)
```


```{r}
urchins <-
  read_csv("https://tidymodels.org/start/models/urchins.csv") %>%
  setNames(c("food_regime", "initial_volume", "width")) %>%
  mutate(food_regime = factor(food_regime, levels = c("Initial", "Low", "High")))
urchins
```


```{r}
urchins %>%
  ggplot(aes(initial_volume, width, group = food_regime, color = food_regime)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  scale_color_viridis_d(option = "plasma", end = .7)
```


```{r}
lm_mod <- 
  linear_reg() %>%
  set_engine("lm")
lm_mod
```


```{r}
lm_fit <- 
  lm_mod %>%
  fit(width ~ initial_volume * food_regime, data = urchins)
lm_fit
```


```{r}
summary(lm_fit$fit)
```


```{r}
tidy(lm_fit)
```

```{r}
new_points <- expand.grid(
  initial_volume = 20, 
  food_regime = c("Initial", "Low", "High"))
new_points
```


```{r}
mean_pred <- predict(lm_fit, new_data = new_points)
mean_pred
```


```{r}
conf_int_pred <- predict(lm_fit,
                         new_data = new_points,
                         type = "conf_int")
conf_int_pred
```


```{r}
plot_data <- 
  new_points %>%
  bind_cols(mean_pred) %>%
  bind_cols(conf_int_pred)

plot_data %>%
  ggplot(aes(food_regime)) +
  geom_point(aes(y = .pred)) +
  geom_errorbar(aes(ymin = .pred_lower, ymax = .pred_upper), width = .2) +
  labs(y = "urchin size")
```


```{r}
prior_dist <- rstanarm::student_t(df = 1)

set.seed(123)

bayes_mod <- 
  linear_reg() %>%
  set_engine("stan",
             prior_intercept = prior_dist,
             prior = prior_dist)

bayes_fit <-
  bayes_mod %>%
  fit(width ~ initial_volume * food_regime, data = urchins)

print(bayes_fit, digits = 5)
```


```{r}
tidy(bayes_fit, intervals = TRUE)
```


```{r}
new_points %>%
  bind_cols(predict(bayes_fit, new_data = new_points)) %>%
  bind_cols(predict(bayes_fit, new_data = new_points, type = "conf_int")) %>%
  ggplot(aes(food_regime)) +
  geom_point(aes(y = .pred)) +
  geom_errorbar(aes(ymin = .pred_lower, ymax = .pred_upper), width = .2) +
  labs(title = "Bayesian model with t(1) prior distribution")
```



```{r}
urchins %>% 
  group_by(food_regime) %>% 
  summarize(med_vol = median(initial_volume), .groups = "drop_last")
```


```{r}
bayes_mod %>% 
  fit(width ~ initial_volume * food_regime, data = urchins)
```


```{r}
urchins %>% 
  ggplot(aes(initial_volume, width)) +
  geom_jitter() +
  geom_smooth(method = lm, se = FALSE) +
  labs(x = "Volue", y = "Width")
```




