---
title: "4. Tune model parameters"
output: html_notebook
date: 2020-11-17
---


```{r setup}
options(
  max.print = 100,
  paged.print = FALSE
)
```


```{r}
library(tidymodels)
library(modeldata)
library(vip)
```


```{r}
data(cells, package = "modeldata")
cells
```


```{r}
set.seed(123)
cell_split <- initial_split(cells %>% select(-case), strata = class)
cell_train <- training(cell_split)
cell_test <- testing(cell_split)
```


```{r}
cell_train
cell_test
```


```{r}
tune_spec <-
  decision_tree(
    cost_complexity = tune(),
    tree_depth = tune()
  ) %>% 
  set_engine("rpart") %>% 
  set_mode("classification")
tune_spec
```


```{r}
tree_grid <- grid_regular(cost_complexity(),
                          tree_depth(),
                          levels = 5)
tree_grid
```


```{r}
tree_grid %>%
  count(tree_depth)
```


```{r}
set.seed(234)
cell_folds <- vfold_cv(cell_train)
cell_folds
```


```{r}
cell_folds$splits[1]
```


```{r}
set.seed(345)
tree_wf <- workflow() %>%
  add_model(tune_spec) %>%
  add_formula(class ~ .)

tree_res <-
  tree_wf %>% 
  tune_grid(
    resamples = cell_folds,
    grid = tree_grid
  )
tree_res
```


```{r}
tree_res %>%
  collect_metrics()
```


```{r}
tree_res %>%
  collect_metrics() %>%
  mutate(tree_depth = factor(tree_depth)) %>%
  ggplot(aes(cost_complexity, mean, color = tree_depth)) +
  geom_line(size = 1.5, alpha = 0.6) +
  geom_point(size = 2) +
  facet_wrap(~ .metric, scales = "free", nrow = 2) +
  scale_x_log10(labels = scales::label_number()) +
  scale_color_viridis_d(option = "plasma", begin = .9, end = 0)
```


```{r}
tree_res %>%
  show_best("roc_auc")
```


```{r}
best_tree <- tree_res %>%
  select_best("roc_auc")
best_tree
```


```{r}
final_wf <-
  tree_wf %>%
  finalize_workflow(best_tree)
final_wf
```


```{r}
final_tree <-
  final_wf %>%
  fit(data = cell_train)
final_tree
```


```{r}
library(vip)
final_tree %>%
  pull_workflow_fit() %>%
  vip()
```


```{r}
final_fit <-
  final_wf %>%
  last_fit(cell_split)

final_fit %>%
  collect_metrics()
```


```{r}
final_fit %>%
  collect_predictions() %>%
  roc_curve(class, .pred_PS) %>%
  autoplot()
```


```{r}
args(decision_tree)
```

