---
title: "Hypothesis testing using resampling and tidy data"
date: 2020-05-22
output: html_notebook
---

```{r}
library(tidyverse)
library(tidymodels)
```


```{r}
data(gss)
gss
```

```{r}
gss %>%
  specify(response = age) %>%
  class()
```

```{r}
gss %>%
  specify(age ~ partyid)
```

```{r}
gss %>%
  specify(response = age, explanatory = partyid)
```

```{r}
gss %>% 
  specify(response = college, success = "degree")
```

```{r}
gss %>% 
  specify(college ~ partyid, success = "degree") %>% 
  hypothesize(null = "independence")
```

```{r}
gss %>% 
  specify(response = hours) %>% 
  hypothesize(null = "point", mu = 40)
```

```{r}
gss %>% 
  specify(response = hours) %>% 
  hypothesize(null = "point", mu = 40) %>% 
  generate(reps = 5000, type = "bootstrap")
```


```{r}
gss %>% 
  specify(partyid ~ age) %>% 
  hypothesize(null = "independence") %>% 
  generate(reps = 5000, type = "permute")
```

```{r}
gss %>%
  specify(response = hours) %>%
  hypothesize(null = "point", mu = 40) %>%
  generate(reps = 5000, type = "bootstrap") %>%
  calculate(stat = "mean")
```

```{r}
gss %>%
  specify(age ~ college) %>%
  hypothesize(null = "independence") %>%
  generate(reps = 5000, type = "permute") %>%
  calculate("diff in means", order = c("degree", "no degree"))
```

```{r}
point_estimate <- gss %>%
  specify(response = hours) %>%
  calculate(stat = "mean")

null_dist <- gss %>% 
  specify(response = hours) %>% 
  hypothesize(null = "point", mu = 40) %>% 
  generate(reps = 5000, type = "bootstrap") %>% 
  calculate(stat = "mean")
```

```{r}
null_dist %>% 
  visualize()
```

```{r}
null_dist %>% 
  visualize() +
  shade_p_value(
    obs_stat = point_estimate, direction = "two_sided"
  )
```


```{r}
# get a two-tailed p-value
p_value <- null_dist %>%
  get_p_value(obs_stat = point_estimate, direction = "two_sided")

p_value


```

```{r}
null_dist %>%
  # calculate the confidence interval around the point estimate
  get_confidence_interval(point_estimate = point_estimate,
                          # at the 95% confidence level
                          level = .95,
                          # using the standard error
                          type = "se")
#> # A tibble: 1 x 2
#>   lower upper
#>   <dbl> <dbl>
#> 1  40.1  41.4
```


```{r}
null_f_distn <- gss %>%
   specify(age ~ partyid) %>%
   hypothesize(null = "independence") %>%
   generate(reps = 5000, type = "permute") %>%
   calculate(stat = "F")
```


```{r}
null_f_distn_theoretical <- gss %>%
   specify(age ~ partyid) %>%
   hypothesize(null = "independence") %>%
   calculate(stat = "F")
```

```{r}
F_hat <- gss %>% 
  specify(age ~ partyid) %>%
  calculate(stat = "F")
```

```{r}
visualize(null_f_distn_theoretical, method = "theoretical") +
  shade_p_value(obs_stat = F_hat, direction = "greater")
```

```{r}
visualize(null_f_distn, method = "both") +
  shade_p_value(obs_stat = F_hat, direction = "greater")
```











