---
title: "Regression models two ways"
date: 2020-05-21
output: html_notebook
---

```{r}
library(tidymodels)
```

```{r}
#install.packages("AmesHousing")
library(AmesHousing)
ames <- make_ames()
```

```{r}
ames
```

```{r}
glimpse(ames)
```

```{r}
data_split <- initial_split(ames, strata = "Sale_Price", p = 0.75)
ames_train <- training(data_split)
ames_test <- testing(data_split)
```

```{r}
ames %>%
  ggplot(aes(Sale_Price)) +
  geom_histogram(color = "white")
```


```{r}
rf_defaults <- rand_forest(mode = "regression")
rf_defaults
```

```{r}
preds <- c("Longitude", "Latitude", "Lot_Area", "Neighborhood", "Year_Sold")

rf_xy_fit <- 
  rf_defaults %>%
  set_engine("ranger") %>%
  fit_xy(
    x = ames_train[, preds],
    y = log10(ames_train$Sale_Price)
  )

rf_xy_fit
```

```{r}
test_results <-
  ames_test %>%
  select(Sale_Price) %>%
  mutate(Sale_Price = log10(Sale_Price)) %>%
  bind_cols(
    predict(rf_xy_fit, new_data = ames_test[, preds])
  )

test_results %>% slice(1:5)
```

```{r}
test_results %>% metrics(truth = Sale_Price, estimate = .pred)
```

```{r}
rand_forest(mode = "regression", mtry = 3, trees = 1000) %>%
  set_engine("ranger") %>%
  fit(
    log10(Sale_Price) ~ Longitude + Latitude + Lot_Area + Neighborhood + Year_Sold,
    data = ames_train
  )
```


```{r}
rand_forest(mode = "regression", mtry = 3, trees = 1000) %>%
  set_engine("randomForest") %>%
  fit(
    log10(Sale_Price) ~ Longitude + Latitude + Lot_Area + Neighborhood + Year_Sold,
    data = ames_train
  )
```

```{r}
rand_forest(mode = "regression", mtry = .preds(), trees = 1000) %>%
  set_engine("ranger") %>%
  fit(
    log10(Sale_Price) ~ Longitude + Latitude + Lot_Area + Neighborhood + Year_Sold,
    data = ames_train
  )
```

```{r}
norm_recipe <-
  recipe(
    Sale_Price ~ Longitude + Latitude + Lot_Area + Neighborhood + Year_Sold,
    data = ames_train
  ) %>%
  step_other(Neighborhood) %>%
  step_dummy(all_nominal()) %>%
  step_center(all_predictors()) %>%
  step_scale(all_predictors()) %>%
  step_log(Sale_Price, base = 10) %>%
  prep(training = ames_train, retain = TRUE)
juice(norm_recipe)
```

```{r}
glmn_fit <-
  linear_reg(penalty = 0.001, mixture = 0.5) %>%
  set_engine("glmnet") %>% 
  fit(Sale_Price ~ ., data = juice(norm_recipe))
glmn_fit
```

```{r}
test_normalized <- bake(norm_recipe, new_data = ames_test, all_predictors())
test_normalized
```

```{r}
test_results <-
  test_results %>%
  rename(random_forest = .pred) %>%
  bind_cols(
    predict(glmn_fit, new_data = test_normalized) %>%
      rename(glmnet = .pred)
  )
test_results
```

```{r}
test_results %>% metrics(truth = Sale_Price, estimate = glmnet)
```

```{r}
test_results %>%
  gather(model, prediction, -Sale_Price) %>% 
  ggplot(aes(prediction, Sale_Price)) +
  geom_abline(col = "green", lty = 2) +
  geom_point(alpha = .4) +
  facet_wrap(~model) +
  coord_fixed()
```













































