---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidymodels)
```

```{r}
# install.packages("keras")
# keras::install_keras()
library(keras)
```

```{r}
data(bivariate)
bivariate_train
bivariate_val
bivariate_test
```

```{r}
ggplot(bivariate_train, aes(x = A, y = B, col = Class)) +
  geom_point(alpha = .2) +
  theme(aspect.ratio = 1)
```

```{r}
biv_rec <-
  recipe(Class ~ ., data = bivariate_train) %>% 
  step_BoxCox(all_predictors()) %>% 
  step_normalize(all_predictors()) %>% 
  prep(training = bivariate_train, retain = TRUE)
juice(biv_rec)
```

```{r}
juice(biv_rec) %>%
  summarize(
    mean = mean(A), 
    sd = sd(A),
    mean2 = mean(B),
    sd2 = sd(B)
  )
```


```{r}
bivariate_train %>%
  pivot_longer(cols = c(A, B)) %>%
  ggplot(aes(value)) +
  geom_histogram() + 
  facet_wrap(~name, scales = "free")
```

```{r}
juice(biv_rec) %>%
  pivot_longer(cols = c(A, B)) %>%
  ggplot(aes(value)) +
  geom_histogram() + 
  facet_wrap(~name, scales = "free")
```


```{r}
val_normalized <- bake(biv_rec, new_data = bivariate_val, all_predictors())
val_normalized
```

```{r}
test_normalized <- bake(biv_rec, new_data = bivariate_test, all_predictors())
test_normalized
```

```{r}
set.seed(57974)
nnet_fit <-
  mlp(epochs = 100, hidden_units = 5, dropout = 0.1) %>% 
  set_mode("classification") %>% 
  set_engine("keras", verbose = 0) %>% 
  fit(Class ~ ., data = juice(biv_rec))
nnet_fit
```

```{r}
val_results <-
  bivariate_val %>% 
  bind_cols(
    predict(nnet_fit, new_data = val_normalized),
    predict(nnet_fit, new_data = val_normalized, type = "prob")
  )
val_results
```

```{r}
val_results %>% roc_auc(truth = Class, .pred_One)
val_results %>% accuracy(truth = Class, .pred_class)
```

```{r}
val_results %>% conf_mat(truth = Class, .pred_class)
```

```{r}
a_rng <- range(bivariate_train$A)
b_rng <- range(bivariate_train$B)
x_grid <- expand.grid(
  A = seq(a_rng[1], a_rng[2], length.out = 100),
  B = seq(b_rng[1], b_rng[2], length.out = 100)
)
x_grid_trans <- bake(biv_rec, x_grid)
x_grid_trans
```

```{r}
x_grid <-
  x_grid %>% 
  bind_cols(predict(nnet_fit, x_grid_trans, type = "prob"))
x_grid
```


```{r}
ggplot(x_grid, aes(x = A, y = B)) +
  geom_contour(aes(z = .pred_One), breaks = .5, col = "black") +
  geom_point(data = bivariate_val, aes(col = Class), alpha = 0.3)
```
















































