---
title: "L3.2 Nested resampling"
output: html_notebook
---


```{r}
options(paged.print = FALSE, max.print = 100)
```


```{r}
library(tidymodels)
library(mlbench)
library(kernlab)
```


```{r}
sim_data <- function(n) {
  tmp <- mlbench.friedman1(n, sd = 1)
  tmp <- cbind(tmp$x, tmp$y)
  tmp <- as.data.frame(tmp)
  names(tmp)[ncol(tmp)] <- "y"
  as_tibble(tmp)
}
```


```{r}
set.seed(9815)
train_dat <- sim_data(100)
large_dat <- sim_data(10^5)
```


```{r}
train_dat
```


```{r}
results <- nested_cv(train_dat, 
                     outside = vfold_cv(repeats = 5),
                     inside = bootstraps(times = 25))
results
```


```{r}
results$inner_resamples[[1]]
```


```{r}
analysis(results$inner_resamples[[1]]$splits[[1]])
```


```{r}
analysis(results$inner_resamples[[1]]$splits[[2]])
```


```{r}
results$splits[[2]]
```


```{r}
results$inner_resamples[[5]]
```


```{r}
results$inner_resamples[[5]]$splits[[1]]
```


```{r}
train <- analysis(results$splits[[1]])
test <- assessment(results$splits[[1]])
```


```{r}
map_dbl(train, mean)
map_dbl(train, sd)
map(train, range)
```


```{r}
svm_rmse <- function(object, cost = 1) {
  y_col <- ncol(object$data)
  mod <- 
    svm_rbf(mode = "regression", cost = cost) %>% 
    set_engine("kernlab") %>% 
    fit(y ~ ., data = analysis(object))
  mod
  
  holdout_pred <-
    predict(mod, assessment(object) %>% select(-y)) %>% 
    bind_cols(assessment(object) %>% select(y))
  rmse(holdout_pred, y, .pred)$.estimate
}
```


```{r}
rmse_wrapper <- function(cost, object) svm_rmse(object, cost)
```


```{r}
rmse_wrapper(1, results$splits[[1]])
```


```{r}
tune_over_cost <- function(object) {
  tibble(cost = 2^seq(-2, 8, by = 1)) %>% 
    mutate(RMSE = map_dbl(cost, rmse_wrapper, object = object))
}
```


```{r}
summarize_tune_results <- function(object) {
  map_df(object$splits, tune_over_cost) %>% 
  group_by(cost) %>% 
  summarize(mean_RMSE = mean(RMSE, na.rm = TRUE),
            n = length(RMSE),
            .groups = "drop")  
}
```


```{r}
# a lot of time needs
#tunning_results <- map(results$inner_resamples, summarize_tune_results)
```


```{r}
library(furrr)
plan(multisession)
```


```{r}
tuning_results <- future_map(results$inner_resamples, summarize_tune_results)
```


```{r}
pooled_inner <- tuning_results %>% bind_rows()

best_cost <- function(dat) dat[which.min(dat$mean_RMSE),]
```


```{r}
p <- 
  ggplot(pooled_inner, aes(cost, mean_RMSE)) +
  scale_x_continuous(trans = 'log2') +
  xlab("SVM Cost") + ylab("Inner RMSE")

for (i in 1:length(tuning_results))
  p <- p +
  geom_line(data = tuning_results[[i]], alpha = .2) +
  geom_point(data = best_cost(tuning_results[[i]]), pch = 16, alpha = 3/4)

p <- p + geom_smooth(data = pooled_inner, se = FALSE)
p
```

```{r}
cost_vals <- 
  tuning_results %>% 
  map_df(best_cost) %>% 
  select(cost)

results <- 
  bind_cols(results, cost_vals) %>% 
  mutate(cost = factor(cost, levels = paste(2 ^ seq(-2, 8, by = 1))))

ggplot(results, aes(x = cost)) + 
  geom_bar() + 
  xlab("SVM Cost") + 
  scale_x_discrete(drop = FALSE)
```


```{r}
results <- 
  results %>% 
  mutate(RMSE = map2_dbl(splits, cost, svm_rmse))

summary(results$RMSE)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>    1.57    2.09    2.68    2.69    3.26    4.27

```


```{r}
not_nested <- 
  future_map(results$splits, tune_over_cost) %>%
  bind_rows()

outer_summary <- not_nested %>% 
  group_by(cost) %>% 
  summarize(outer_RMSE = mean(RMSE), n = length(RMSE))

outer_summary

ggplot(outer_summary, aes(x = cost, y = outer_RMSE)) + 
  geom_point() + 
  geom_line() + 
  scale_x_continuous(trans = 'log2') +
  xlab("SVM Cost") + ylab("RMSE")

```


```{r}
finalModel <- ksvm(y ~ ., data = train_dat, C = 2)
large_pred <- predict(finalModel, large_dat[, -ncol(large_dat)])
sqrt(mean((large_dat$y - large_pred) ^ 2, na.rm = TRUE))
#> [1] 2.71
```




















