---
title: "L3.3 Iterative Bayesian optimization of a classification model"
output: html_notebook
---


```{r}
options(paged.print = FALSE, max.print = 100)
```


```{r}
library(tidymodels)
library(modeldata)
```


```{r}
data(cells)
set.seed(2369)
tr_te_split <- initial_split(cells %>% select(-case), prop = 3/4)
cell_train <- training(tr_te_split)
cell_test <- testing(tr_te_split)

set.seed(1697)
folds <- vfold_cv(cell_train, v = 10)
```


```{r}
library(themis)
cell_pre_proc <-
  recipe(class ~ ., data = cell_train) %>%
  step_YeoJohnson(all_predictors()) %>% 
  step_normalize(all_predictors()) %>% 
  step_pca(all_predictors(), num_comp = tune()) %>% 
  step_downsample(class)
```


```{r}
svm_mod <-
  svm_rbf(mode = "classification", cost = tune(), rbf_sigma = tune()) %>% 
  set_engine("kernlab")
```


```{r}
svm_wflow <-
  workflow() %>% 
  add_model(svm_mod) %>% 
  add_recipe(cell_pre_proc)
```


```{r}
svm_set <- parameters(svm_wflow)
svm_set
```


```{r}
set.seed(12)
search_res <-
  svm_wflow %>% 
  tune_bayes(
    resamples = folds,
    param_info = svm_set,
    initial = 5,
    iter = 50,
    metrics = metric_set(roc_auc),
    control = control_bayes(no_improve = 30, verbose = TRUE)
  )
```


```{r}
search_res
```


```{r}
estimates <-
  collect_metrics(search_res) %>% 
  arrange(.iter)
estimates
```


```{r}
show_best(search_res, metric = "roc_auc")
```


```{r}
autoplot(search_res, type = "performance")
```


```{r}
autoplot(search_res, type = "parameters") +
  labs(x = "Iterations", y = NULL)
```

