---
title: "rsample"
output: html_notebook
---


```{r setup}
options(max.print = 100, paged.print = FALSE)
```


```{r}
library(tidymodels)
```


## Overview

```{r}
library(rsample)
library(mlbench)
library(lobstr)
library(tidymodels)
```


```{r}
data("LetterRecognition")
obj_size(LetterRecognition)
```


```{r}
object.size(LetterRecognition)
```


```{r}
set.seed(35222)
boots <- bootstraps(LetterRecognition, times = 50)
obj_size(boots)
```


```{r}
object.size(boots)
```


```{r}
obj_size(boots)/nrow(boots)
```


```{r}
as.numeric(obj_size(boots)/obj_size(LetterRecognition))
```


```{r}
boots
```


```{r}
boots$splits[[1]]
```


```{r}
str(boots$splits[[1]])
```


```{r}
dim(analysis(boots$splits[[1]]))
```


```{r}
dim(assessment(boots$splits[[1]]))
```


```{r}
dim(assessment(boots$splits[[2]]))
```


## Basics

```{r}
set.seed(8584)
bt_resamples <- bootstraps(mtcars, times = 3)
bt_resamples
```


```{r}
class(bt_resamples)
```


```{r}
first_resample <- bt_resamples$splits[[1]]
first_resample
```


```{r}
as.data.frame(first_resample)
```


```{r}
as.data.frame(first_resample, data = "assessment")
```


```{r}
analysis(first_resample)
```


```{r}
assessment(first_resample)
```


## Working with rsets

### Intdocution

```{r}
data("attrition", package = "modeldata")
names(attrition)
table(attrition$Attrition)
```


```{r}
glm(Attrition ~ JobSatisfaction + Gender + MonthlyIncome, data = attrition, 
    family = binomial)
```


```{r}
mod_form <- as.formula(Attrition ~ JobSatisfaction + Gender + MonthlyIncome)
```


```{r}
set.seed(4622)
rs_obj <- vfold_cv(attrition, v = 10, repeats = 10)
rs_obj
```


```{r}
holdout_results <- function(splits, ...) {
  mod <- glm(..., data = analysis(splits), family = binomial)
  holdout <- assessment(splits)
  res <- broom::augment(mod, newdata = holdout)
  lvls <- levels(holdout$Attrition)
  predictions <- factor(ifelse(res$.fitted >0, lvls[2], lvls[1]), levels = lvls)
  res$correct <- predictions == holdout$Attrition
  res
}
```


```{r}
example <- holdout_results(rs_obj$splits[[1]], mod_form)
dim(example)
dim(assessment(rs_obj$splits[[1]]))
example[1:10, setdiff(names(example), names(attrition))]
```


```{r}
holdout_results <- function(splits, ...) {
  mod <- glm(..., data = analysis(splits), family = binomial)
  holdout <- assessment(splits)
  res <- broom::augment(mod, newdata = holdout)
  lvls <- levels(holdout$Attrition)
  predictions <- factor(ifelse(res$.fitted >0, lvls[2], lvls[1]), levels = lvls)
  res$correct <- predictions == holdout$Attrition
  res
}

example <- holdout_results(rs_obj$splits[[1]], mod_form)
dim(example)
dim(assessment(rs_obj$splits[[1]]))
example[1:10, setdiff(names(example), names(attrition))]
```


```{r, paged.print = TRUE}
splits <- rs_obj$splits[[1]]
mod <- glm(mod_form, data = analysis(splits), family = binomial)
holdout <- assessment(splits)
holdout
```


```{r, paged.print = TRUE}
res <- broom::augment(mod, newdata = holdout)
res
```


```{r}
lvls <- levels(holdout$Attrition)
predictions <- factor(ifelse(res$.fitted >0, lvls[2], lvls[1]), levels = lvls)
predictions
```


```{r}
res$correct <- predictions == holdout$Attrition
res[, setdiff(names(example), names(attrition))]
```


```{r}
library(purrr)
rs_obj$results <- map(rs_obj$splits, holdout_results, mod_form)
rs_obj
```


```{r}
rs_obj$accuracy <- map_dbl(rs_obj$results, function(x) mean(x$correct))
summary(rs_obj$accuracy)
```


```{r}
hist(rs_obj$accuracy)
```


### Using the bootstrap to make comparisons

```{r}

```


```{r}
ggplot(attrition, aes(Gender, MonthlyIncome)) +
  geom_boxplot() +
  scale_y_log10()
```


```{r}
median_diff <- function(splits) {
  x <- analysis(splits)
  median(x$MonthlyIncom[x$Gender == "Female"]) -
    median(x$MonthlyIncome[x$Gender == "Male"])
}
```


```{r}
set.seed(353)
bt_resamples <- bootstraps(attrition, times = 500)
```


```{r}
bt_resamples$wage_diff <- map_dbl(bt_resamples$splits, median_diff)
bt_resamples
```


```{r}
ggplot(bt_resamples, aes(wage_diff)) +
  geom_density(adjust = 1.25) +
  xlab("Difference in Median Montly Income (Female - Male)")
```


```{r}
glm_coefs <- function(splits, ...) {
  mod <- glm(..., data = analysis(splits), family = binomial)
  as.data.frame(t(coef(mod)))
}
bt_resamples$betas <- map(bt_resamples$splits, glm_coefs, mod_form)
bt_resamples
```


### Keeping tidy

```{r}
first_resample <- bt_resamples$splits[[1]]
class(first_resample)
```


```{r}
tidy(first_resample)
```


```{r}
class(bt_resamples)
```


```{r}
tidy(bt_resamples)
```


## Recipes with rsample

```{r}
library(AmesHousing)
ames <- make_ames()
ames
```


```{r}
theme_set(theme_bw())
ggplot(ames, aes(Lot_Area)) +
  geom_histogram(bindwidth = 5000, col = "red", fill = "red", alpha = .5)
```


```{r}
ggplot(ames, aes(Neighborhood)) + geom_bar() + coord_flip() + xlab("")
```


```{r}
library(recipes)
rec <- 
  recipe(Sale_Price ~ Neighborhood + House_Style + Year_Sold + Lot_Area,
         data = ames) %>% 
  step_log(Sale_Price, base = 10) %>% 
  step_other(Neighborhood, House_Style, threshold = 0.05) %>% 
  step_dummy(all_nominal()) %>% 
  step_BoxCox(Lot_Area) %>% 
  step_center(all_predictors()) %>% 
  step_scale(all_predictors())
rec
```


```{r}
rec_training_set <- prep(rec, training = ames)
rec_training_set
```


```{r}
bake(rec_training_set, new_data = head(ames))
```


```{r}
juice(rec_training_set)
```


```{r}
set.seed(7712)
bt_samples <- bootstraps(ames)
bt_samples
```


```{r}
bt_samples$splits[[1]]
```


```{r}
bt_samples$recipes <- map(bt_samples$splits, prepper, recipe = rec)
bt_samples
```


```{r}
dim(juice(bt_samples$recipes[[1]], everything()))
```


```{r}
fit_lm <- function(rec_obj, ...)
  lm(..., data = juice(rec_obj, everything()))

bt_samples$lm_mod <- 
  map(
    bt_samples$recipes,
    fit_lm,
    Sale_Price ~ .
  )
bt_samples
```


```{r}
pred_lm <- function(split_obj, rec_obj, model_obj, ...) {
  mod_data <- bake(
    rec_obj, 
    new_data = assessment(split_obj),
    all_predictors(),
    all_outcomes()
  ) 
  
  out <- mod_data %>% select(Sale_Price)
  out$predicted <- predict(model_obj, newdata = mod_data %>% select(-Sale_Price))
  out
}

bt_samples$pred <- 
  pmap(
    lst(
      split_obj = bt_samples$splits, 
      rec_obj = bt_samples$recipes, 
      model_obj = bt_samples$lm_mod
    ),
    pred_lm 
  )
bt_samples
```


```{r}
results <- map_dfr(bt_samples$pred, rmse, Sale_Price, predicted)
results
```


```{r}
mean(results$.estimate)
```


## Survival Analysis Example

```{r}
library(survival)
str(lung)
```


```{r}
lung_mod <- survreg(Surv(time, status) ~ ph.ecog + age + strata(sex), data = lung)
summary(lung_mod)
```


```{r}
coef(lung_mod)
```


```{r}
library(rsample)
set.seed(9666)
mc_samp <- mc_cv(lung, strata = "status", times = 100)

library(purrr)
cens_rate <- function(x) mean(analysis(x)$status == 1)
summary(map_dbl(mc_samp$splits, cens_rate))
```


```{r}
library(purrr)
cens_rate <- function(x) mean(analysis(x)$status == 1)
summary(map_dbl(mc_samp$splits, cens_rate))
```


```{r}
three_fact <- as.formula(Surv(time, status) ~ ph.ecog + age + strata(sex))
rm_ph.ecog <- as.formula(Surv(time, status) ~           age + strata(sex))
rm_age     <- as.formula(Surv(time, status) ~ ph.ecog +       strata(sex))
rm_sex     <- as.formula(Surv(time, status) ~ ph.ecog + age              )
```


```{r}
mod_fit <- function(x, form, ...) 
  survreg(form, data = analysis(x), ...)
```


```{r}
get_concord <- function(split, mod, ...) {
  pred_dat <- assessment(split)
  pred_dat$pred <- predict(mod, newdata = pred_dat)
  concordance(Surv(time, status) ~ pred, pred_dat, ...)$concordance
}
```


```{r}
mc_samp$mod_full    <- map(mc_samp$splits, mod_fit, form = three_fact)
mc_samp$mod_ph.ecog <- map(mc_samp$splits, mod_fit, form = rm_ph.ecog)
mc_samp$mod_age     <- map(mc_samp$splits, mod_fit, form = rm_age)
mc_samp$mod_sex     <- map(mc_samp$splits, mod_fit, form = rm_sex)
```


```{r}
mc_samp$full    <- map2_dbl(mc_samp$splits, mc_samp$mod_full, get_concord)
mc_samp$ph.ecog <- map2_dbl(mc_samp$splits, mc_samp$mod_ph.ecog, get_concord)
mc_samp$age     <- map2_dbl(mc_samp$splits, mc_samp$mod_age, get_concord)
mc_samp$sex     <- map2_dbl(mc_samp$splits, mc_samp$mod_sex, get_concord)
```


```{r}
library(dplyr)
concord_est <- mc_samp %>%
  dplyr::select(-matches("^mod"))

library(tidyr)
library(ggplot2)
concord_est %>%
  gather() %>%
  ggplot(aes(x = statistic, col = model)) + 
  geom_line(stat = "density") + 
  theme_bw() + 
  theme(legend.position = "top")
```

```{r}
#install.packages("tidyposterior")
library(tidyposterior)
concord_est <- perf_mod(concord_est, seed = 6507, iter = 5000)
```

```{r}
concord_est$stan
```


```{r}
ggplot(tidy(concord_est)) + 
  theme_bw()
```


```{r}
comparisons <- contrast_models(
  concord_est, 
  list_1 = rep("full", 3),
  list_2 = c("ph.ecog", "age", "sex"),
  seed = 4654
  )
```


```{r}
ggplot(comparisons, size = 0.05) + 
  theme_bw()
```

```{r}
summary(comparisons, size = 0.05) %>%
  dplyr::select(contrast, starts_with("pract"))
```


## Bootstrap Confidence Intervals

```{r}
library(tidymodels)
library(nlstools)
library(GGally)

data(O2K)

ggplot(O2K, aes(x = t, y = VO2)) + 
  geom_point()
```


```{r}
nonlin_form <-  
  as.formula(
    VO2 ~ (t <= 5.883) * VO2rest + 
      (t > 5.883) * 
      (VO2rest + (VO2peak - VO2rest) * (1 - exp(-(t - 5.883) / mu)))
    )

# Starting values from visual inspection
start_vals <- list(VO2rest = 400, VO2peak = 1600, mu = 1)

res <- nls(nonlin_form, start = start_vals, data = O2K) 

tidy(res)
```

```{r}
# Will be used to fit the models to different bootstrap data sets:
fit_fun <- function(split, ...) {
  # We could check for convergence, make new parameters, etc.
  nls(nonlin_form, data = analysis(split), ...) %>%
    tidy()
}
```


```{r}
set.seed(462)
nlin_bt <-
  bootstraps(O2K, times = 2000, apparent = TRUE) %>%
  mutate(models = map(splits, ~ fit_fun(.x, start = start_vals)))
nlin_bt
```


```{r}
nlin_bt$models[[1]]
```


```{r}
library(tidyr)
nls_coef <- 
  nlin_bt %>%
  dplyr::select(-splits) %>%
  # Turn it into a tibble by stacking the `models` col
  unnest() %>%
  # Get rid of unneeded columns
  dplyr::select(id, term, estimate) 
```


```{r}
nls_coef
```


```{r}
nls_coef %>%
  # Put different parameters in columns
  tidyr::spread(term, estimate) %>% 
  # Keep only numeric columns
  dplyr::select(-id) %>% 
  ggscatmat(alpha = .25)
```


```{r}
nls_coef %>% 
  ggplot(aes(x = estimate)) + 
  geom_histogram(bins = 20, col = "white") + 
  facet_wrap(~ term, scales = "free_x")
```


```{r}
p_ints <- int_pctl(nlin_bt, models)
p_ints
```


```{r}
nls_coef %>% 
  ggplot(aes(x = estimate)) + 
  geom_histogram(bins = 20, col = "white") + 
  facet_wrap(~ term, scales = "free_x") + 
  geom_vline(data = p_ints, aes(xintercept = .lower), col = "red") + 
  geom_vline(data = p_ints, aes(xintercept = .upper), col = "red")
```


```{r}
parametric <- 
  tidy(res, conf.int = TRUE) %>% 
  dplyr::select(
    term,
    .lower = conf.low,
    .estimate = estimate,
    .upper = conf.high
  ) %>% 
  mutate(
    .alpha = 0.05,
    .method = "parametric"
  )

intervals <- 
  bind_rows(parametric, p_ints) %>% 
  arrange(term, .method)
intervals %>% split(intervals$term)
```


```{r}
nls_coef %>% 
  ggplot(aes(sample = estimate)) + 
  stat_qq() +
  stat_qq_line(alpha = .25) + 
  facet_wrap(~ term, scales = "free") 
```


```{r}
t_stats <- int_t(nlin_bt, models)
intervals <- 
  bind_rows(intervals, t_stats) %>% 
  arrange(term, .method)
intervals %>% split(intervals$term)
```


```{r}
bias_corr <- int_bca(nlin_bt, models, .fn = fit_fun, start = start_vals)
intervals <- 
  bind_rows(intervals, bias_corr) %>% 
  arrange(term, .method)
intervals %>% split(intervals$term)
```


```{r}
fold_incr <- function(split, ...) {
  dat <- analysis(split)
  quants <- quantile(dat$VO2, probs = c(.1, .9))
  tibble(
    term = "fold increase",
    estimate = unname(quants[2]/quants[1]),
    # We don't know the analytical formula for this 
    std.error = NA_real_
  )
}
```


```{r}
nlin_bt <-
  nlin_bt %>%
  mutate(folds = map(splits, fold_incr))

int_pctl(nlin_bt, folds)
```


```{r}
int_bca(nlin_bt, folds, .fn = fold_incr)
```














