---
title: "Basics"
output: html_notebook
date: 2020-11-25
---


```{r}
options(paged.print = FALSE, max.print = 100)
```


# 3 A review of R modeling fundamentals

```{r}
library(tidyverse)
```


```{r}
data(crickets, package = "modeldata")
crickets
```


```{r}
crickets %>% 
ggplot(aes(temp, rate, color = species)) +
  geom_point() +
  geom_smooth(method = lm, se = FALSE) +
  labs(x = "Temperture (C)", y = "Chirp Rate (per minute)")
```


```{r}
interaction_fit <- lm(rate ~ (temp + species)^2, data = crickets)
summary(interaction_fit)
```


```{r}
par(mfrow = c(2, 2))
plot(interaction_fit)
```


```{r}
main_effect_fit <- lm(rate ~ temp + species, data = crickets)

anova(main_effect_fit, interaction_fit)
```


```{r}
summary(main_effect_fit)
```


```{r}
new_values <- data.frame(species = "O. exclamationis", temp = 15:20)
predict(main_effect_fit, newdata = new_values)
```


```{r}
new_values$temp[1] <- NA
```


```{r}
predict(main_effect_fit, new_values)
```


```{r}
#predict(main_effect_fit, new_values, na.action = na.fail)
```


```{r}
predict(main_effect_fit, new_values, na.action = na.omit)
```


```{r}
corr_res <- map(mtcars %>% select(-mpg), cor.test, y = mtcars$mpg)
corr_res
```


```{r}
library(broom)
tidy(corr_res[[1]])
```


```{r}
corr_res %>% 
  map_dfr(tidy, .id = "predictor") %>% 
  ggplot(aes(fct_reorder(predictor, estimate))) +
  geom_point(aes(y = estimate)) +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = .1) +
  labs(x = NULL, y = "Correlation with mpg")
```


```{r}
split_by_species <-
  crickets %>% 
  group_nest(species)
split_by_species
```


```{r}
model_by_species <-
  split_by_species %>% 
  mutate(model = map(data, ~lm(rate ~ temp, data = .x)))
model_by_species
```


```{r}
model_by_species %>% 
  mutate(coef = map(model, tidy)) %>% 
  select(species, coef) %>% 
  unnest(coef)
```


# 4 The Ames housing data

```{r}
library(tidyverse)
library(tidymodels)
```


```{r}
library(modeldata)
data(ames)
ames
```


```{r}
ames %>% 
  ggplot(aes(Sale_Price)) +
  geom_histogram(bins = 50)
```


```{r}
ames %>% 
  ggplot(aes(Sale_Price)) +
  geom_histogram(bins = 50) +
  scale_x_log10()
```


```{r}
ames <-
  ames %>% 
  mutate(Sale_Price = log10(Sale_Price))
```


# 5 Spdeing our data

```{r}
set.seed(123)
ames_split <- initial_split(ames, prob = 0.8, strata = Sale_Price)
ames_split
```


```{r}
ames_train <- training(ames_split)
ames_test <- testing(ames_split)

dim(ames_train)
```


# 6 Feature engineering with recipes

```{r}
#lm(Sale_Price ~ Neighborhood + log10(Gr_Liv_Area) + Year_built + Bldg_Type)
```


```{r}
simple_ames <-
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type,
         data = ames_train) %>% 
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_dummy(all_nominal())
simple_ames
```


```{r}
simple_ames <- prep(simple_ames, training = ames_train)
simple_ames
```


```{r}
test_ex <- bake(simple_ames, new_data = NULL)
test_ex
```


```{r}
bake(simple_ames, ames_test, starts_with("Neighborhood_"))
```


```{r}
bake(simple_ames, new_data = NULL)
```


```{r}
ggplot(ames_train, aes(y = Neighborhood)) +
  geom_bar() +
  labs(y = NULL)
```


```{r}
simple_ames <-
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type,
         data = ames_train) %>% 
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal())
```


```{r}
ames_train %>% 
  ggplot(aes(Gr_Liv_Area, 10^Sale_Price)) +
  geom_point(alpha = .2) +
  facet_wrap(~Bldg_Type) +
  geom_smooth(method = lm, formula = y ~ x, se = FALSE, col = "red") +
  scale_x_log10() +
  scale_y_log10() +
  labs(x = "General Living Area", y = "Sale Price (USD)")
```


```{r}
library(patchwork)
library(splines)

plot_smoother <- function(deg_free) {
  ggplot(ames_train, aes(Latitude, Sale_Price)) +
    geom_point(alpha = .2) +
    scale_y_log10() +
    geom_smooth(
      method = lm,
      formula = y ~ ns(x, df = deg_free),
      col = "red",
      se = FALSE
    ) +
    ggtitle(paste(deg_free, "Spline Terms"))
}

(plot_smoother(2) + plot_smoother(5)) / (plot_smoother(20) + plot_smoother(100))
```


```{r}
ames_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal()) %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) %>% 
  step_ns(Latitude, Longitude, deg_free = 20)
```


```{r}
ames_rec_prepped <- prep(ames_rec)
ames_train_prepped <- bake(ames_rec_prepped, new_data = NULL)
ames_test_prepped <- bake(ames_rec_prepped, ames_test)
```


```{r}
lm_fit <- lm(Sale_Price ~ ., data = ames_train_prepped)
```


```{r}
glance(lm_fit)
```


```{r}
ames_train_prepped
```


```{r}
tidy(lm_fit)
```


```{r}
pred <- predict(lm_fit, ames_test_prepped)
```


```{r}
ames_test_prepped %>% 
  select(Sale_Price) %>% 
  mutate(estimate = pred) %>% 
  mutate(
    sp = 10^Sale_Price,
    es = 10^estimate
  ) %>% 
  ggplot(aes(Sale_Price, Sale_Price - estimate)) +
  geom_point(alpha = .1)
```


```{r}
tidy(ames_rec_prepped)
```


```{r}
ames_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10, id = "my_id") %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal()) %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) %>% 
  step_ns(Latitude, Longitude, deg_free = 20)

ames_rec_prepped <- prep(ames_rec)
```


```{r}
tidy(ames_rec_prepped)
```


```{r}
tidy(ames_rec_prepped, number = 2)
```


```{r}
library(tidymodels)
data(ames)
ames <- mutate(ames, Sale_Price = log10(Sale_Price))

set.seed(123)
ames_split <- initial_split(ames, prob = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

ames_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal()) %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) %>% 
  step_ns(Latitude, Longitude, deg_free = 20)
```


# 7 Fitting models with parsnip

```{r}
lm_model <-
  linear_reg() %>% 
  set_engine("lm")
```


```{r}
lm_form_fit <-
  lm_model %>% 
  fit(Sale_Price ~ Longitude + Latitude, data = ames_train)
lm_form_fit
```


```{r}
lm_xy_fit <-
  lm_model %>% 
  fit_xy(
    x = ames_train %>% select(Longitude, Latitude),
    y = ames_train %>% pull(Sale_Price)
  )
lm_xy_fit
```


```{r}
rand_forest(trees = 1000, min_n = 5) %>% 
  set_engine("ranger") %>% 
  set_mode("regression") %>% 
  translate()
```


```{r}
rand_forest(trees = 1000, min_n = 5) %>% 
  set_engine("randomForest") %>% 
  set_mode("regression") %>% 
  translate()
```


```{r}
lm_form_fit$fit %>% vcov()
```


```{r}
model_res <-
  lm_form_fit %>% 
  pluck("fit") %>% 
  summary()

param_est <- coef(model_res)
class(param_est)

param_est
```


```{r}
tidy(lm_form_fit)
```


```{r}
ames_test_small <- ames_test %>% slice(1:5)
predict(lm_form_fit, new_data = ames_test_small)
```


```{r}
ames_test_small %>% 
  select(Sale_Price) %>% 
  bind_cols(predict(lm_form_fit, ames_test_small)) %>% 
  bind_cols(predict(lm_form_fit, ames_test_small, type = "pred_int"))
```


```{r}
tree_model <-
  decision_tree(min_n = 2) %>% 
  set_engine("rpart") %>% 
  set_mode("regression")

tree_fit <- tree_model %>% 
  fit(Sale_Price ~ Longitude + Latitude, data = ames_train)

ames_test_small %>% 
  select(Sale_Price) %>% 
  bind_cols(predict(tree_fit, ames_test_small))
```


# 8 A model workflow

```{r}
lm_model <-
  linear_reg() %>% 
  set_engine("lm")
```


```{r}
lm_wflow <-
  workflow() %>% 
  add_model(lm_model)
lm_wflow
```


```{r}
lm_wflow <-
  lm_wflow %>% 
  add_formula(Sale_Price ~ Longitude + Latitude)
lm_wflow
```


```{r}
lm_fit <- fit(lm_wflow, ames_train)
lm_fit
```


```{r}
predict(lm_fit, ames_test %>% slice(1:3))
```


```{r}
lm_fit %>% update_formula(Sale_Price ~ Longitude)
```


```{r}
lm_wflow <- 
  lm_wflow %>% 
  remove_formula() %>% 
  add_recipe(ames_rec)
lm_wflow
```


```{r}
lm_fit <- fit(lm_wflow, ames_train)

predict(lm_fit, ames_test %>% slice(1:3))
```


```{r}
lm_fit %>% 
  pull_workflow_prepped_recipe() %>% 
  tidy()
```


```{r}
lm_fit %>% 
  pull_workflow_fit() %>% 
  tidy()
```


```{r}
library(lme4)
data(Orthodont, package = "nlme")
lmer(distance ~ Sex + (age | Subject), data = Orthodont)
```


```{r}
model.matrix(distance ~ Sex + (age | Subject), data = Orthodont)
```


```{r}
library(survival)

parametric_model <-
  surv_reg() %>% 
  set_engine("survival")
```


```{r}
parametric_workflow <-
  workflow() %>% 
  add_formula(futime + fustat ~ age + rx) %>% 
  add_model(parametric_model,
            formula = Surv(futime, fustat) ~ age + strata(rx))

random_effects <- fit(parametric_workflow, data = ovarian)
random_effects
```


```{r}
parametric_workflow <-
  workflow() %>% 
  add_recipe(recipe(futime + fustat ~ age + rx, data = ovarian)) %>% 
  add_model(parametric_model,
            formula = Surv(futime, fustat) ~ age + strata(rx))

random_effects <- fit(parametric_workflow, data = ovarian)
random_effects
```


```{r}
library(tidymodels)
data(ames)

ames <- mutate(ames, Sale_Price = log10(Sale_Price))

set.seed(123)
ames_split <- initial_split(ames, prob = 0.80, strata = Sale_Price)
ames_train <- training(ames_split)
ames_test  <-  testing(ames_split)

ames_rec <- 
  recipe(Sale_Price ~ Neighborhood + Gr_Liv_Area + Year_Built + Bldg_Type + 
           Latitude + Longitude, data = ames_train) %>%
  step_log(Gr_Liv_Area, base = 10) %>% 
  step_other(Neighborhood, threshold = 0.01) %>% 
  step_dummy(all_nominal()) %>% 
  step_interact( ~ Gr_Liv_Area:starts_with("Bldg_Type_") ) %>% 
  step_ns(Latitude, Longitude, deg_free = 20)

lm_model <- linear_reg() %>% set_engine("lm")

lm_wflow <- 
  workflow() %>% 
  add_model(lm_model) %>% 
  add_recipe(ames_rec)

lm_fit <- fit(lm_wflow, ames_train)
```


# 9 Judging model effectiveness

```{r}
ames_test_res <- predict(lm_fit, new_data = ames_test %>% select(-Sale_Price))
ames_test_res
```


```{r}
ames_test_res <- bind_cols(ames_test_res, ames_test %>% select(Sale_Price))
ames_test_res
```


```{r}
ames_test_res %>% 
  ggplot(aes(Sale_Price, .pred)) +
  geom_abline(lty = 2) +
  geom_point(alpha = 0.5) +
  labs(x = "Sale Price (log10)", y = "Predicted Sale Price (log10)") +
  coord_obs_pred()
```


```{r}
rmse(ames_test_res, truth = Sale_Price, estimate = .pred)
```


```{r}
ames_test_res %>% 
  metrics(truth = Sale_Price, estimate = .pred)
```


```{r}
ames_metrics <- metric_set(rmse, rsq, mae)
ames_test_res %>% 
  ames_metrics(truth = Sale_Price, estimate = .pred)
```


```{r}
data(two_class_example)
str(two_class_example)
two_class_example
```


```{r}
conf_mat(two_class_example, truth = truth, estimate = predicted)
```


```{r}
accuracy(two_class_example, truth = truth, estimate = predicted)
```


```{r}
mcc(two_class_example, truth, predicted)
```


```{r}
f_meas(two_class_example, truth, predicted)
```


```{r}
f_meas(two_class_example, truth, predicted, event_level = "second")
```


```{r}
two_class_curve <- roc_curve(two_class_example, truth, Class1)
two_class_curve
roc_auc(two_class_example, truth, Class1)
```


```{r}
autoplot(two_class_curve)
```


```{r}
data(hpc_cv)
glimpse(hpc_cv)
```


```{r}
accuracy(hpc_cv, obs, pred)
```


```{r}
mcc(hpc_cv, obs, pred)
```


```{r}
class_totals <-
  count(hpc_cv, obs, name = "totals") %>% 
  mutate(class_wts = totals / sum(totals))
class_totals
```


```{r}
cell_counts <-
  hpc_cv %>% 
  group_by(obs, pred) %>% 
  count() %>% 
  ungroup()
cell_counts
```


```{r}
one_versus_all <-
  cell_counts %>% 
  filter(obs == pred) %>% 
  full_join(class_totals, by = "obs") %>% 
  mutate(sens = n / totals)
one_versus_all
```


```{r}
one_versus_all %>% 
  summarize(
    macro = mean(sens),
    macro_wts = weighted.mean(sens, class_wts),
    micro = sum(n) / sum(totals)
  )
```


```{r}
sensitivity(hpc_cv, obs, pred, estimator = "macro")
```


```{r}
sensitivity(hpc_cv, obs, pred, estimator = "macro_weighted")
```


```{r}
sensitivity(hpc_cv, obs, pred, estimator = "micro")
```


```{r}
roc_auc(hpc_cv, obs, VF, F, M, L)
```


```{r}
roc_auc(hpc_cv, obs, VF, F, M, L, estimator = "macro_weighted")
```


```{r}
hpc_cv %>% 
  group_by(Resample) %>% 
  accuracy(obs, pred)
```


```{r}
hpc_cv %>% 
  group_by(Resample) %>% 
  roc_curve(obs, VF, F, M, L) %>% 
  autoplot()
```



