---
title: "rules 0.0.1"
output: html_notebook
---

```{r}
#install.packages("rules")
#library(tidyverse)
library(tidymodels)
library(rules)
```

```{r}
library(doParallel)
all_cores <- parallel::detectCores(logical = FALSE)
cl <- makeForkCluster(all_cores)
#cl <- makePSOCKcluster(all_cores)
registerDoParallel(cl)
foreach::getDoParWorkers()
```


```{r}
data(car_prices, package = "modeldata")
car_prices
```

```{r}
set.seed(9932)
car_split <- initial_split(car_prices)
car_train <- training(car_split)
car_test <- testing(car_split)
```

```{r}
car_train
car_test
```


```{r}
cubist_mod <- 
  cubist_rules(neighbors = 9, committees = 9) %>% 
  set_engine("Cubist")
cubist_mod
```

```{r}
cubist_fit <-
  cubist_mod %>% 
  fit(log10(Price) ~ ., data = car_train)
#summary(cubist_fit$fit)
summary(cubist_fit)
```


```{r}
cb_grid <- expand.grid(committees = 1:30, neighbors = c(1 ,3, 5, 7, 9))
cb_grid
```

```{r}
set.seed(8226)
car_folds <- vfold_cv(car_train)
car_folds
car_folds$splits[[1]]
```

```{r}
cubist_mod <-
  cubist_rules(neighbors = tune(), committees = tune()) %>% 
  set_engine("Cubist")
cubist_mod
```

```{r}
car_tune_res <-
  cubist_mod %>% 
  tune_grid(log10(Price) ~ ., resamples = car_folds, grid = cb_grid)
```

```{r}
car_tune_res %>% 
  collect_metrics() %>% 
  filter(.metric == "rmse") %>% 
  mutate(neighbors = factor(neighbors)) %>% 
  ggplot(aes(x = committees, y = mean, col = neighbors)) +
  geom_point() +
  geom_line() +
  scale_color_brewer(palette = "Dark2") +
  theme(legend.position = "top")
```

```{r}
car_tune_res %>% 
  show_best(metric = "rmse")
```


```{r}
smallest_rmse <- select_best(car_tune_res, metric = "rmse")
smallest_rmse
```

```{r}
final_cb_mod <-
  cubist_mod %>% 
  finalize_model(smallest_rmse) %>% 
  fit(log10(Price) ~ ., data = car_train)
```


```{r}
test_pred <-
  predict(final_cb_mod, car_test) %>% 
  bind_cols(car_test %>% select(Price)) %>% 
  mutate(Price = log10(Price))
test_pred
```

```{r}
test_pred %>% rmse(Price, .pred)
```

```{r}
ggplot(test_pred, aes(x = .pred, y = Price)) +
  geom_abline(col = "green", lty = 2) +
  geom_point(alpha = 0.5) +
  coord_fixed(ratio = 1)
```



## rule_fit

```{r}
rule_mod <- 
  rule_fit() %>% 
  set_mode("regression")
  #set_engine("Cubist")
rule_mod
```

```{r}
rule_fit <-
  rule_mod %>% 
  fit(log10(Price) ~ ., data = car_train)
summary(rule_fit)
summary(rule_fit$fit)
```


```{r}
predict(rule_fit, new_data = car_train) %>% 
  bind_cols(car_train %>% select(Price)) %>% 
  summarize(
    sqrt(mean((.pred - Price)^2))
  )
```


```{r}
predict(cubist_fit, new_data = car_train)
predict(rule_fit, new_data = car_train)
# %>% 
#   mutate(.pred = 10^.pred) %>% 
#   bind_cols(car_train %>% select(Price)) %>% 
#   summarize(
#     sqrt(mean((.pred - Price)^2))
#   )
```

```{r}
cubist_fit
```





```{r}
data(car_prices, package = "modeldata")
set.seed(9932)
car_split <- initial_split(car_prices)
car_train <- training(car_split)
car_test <- testing(car_split)

cubist_fit <-
  cubist_rules(neighbors = 9, committees = 9) %>% 
  set_engine("Cubist") %>% 
  fit(log10(Price) ~ ., data = car_train)

rulefit_fit <-
  rule_fit() %>% 
  set_mode("regression") %>%
  fit(log10(Price) ~ ., data = car_train)

res <- 
  bind_cols(
    predict(cubist_fit, new_data = car_train),
    predict(rulefit_fit, new_data = car_train)
  ) %>% 
  rename(cubist = .pred, rulefit = .pred1)
res
```

