---
title: "workflows getting started"
output: html_notebook
---

```{r}
library(tidyverse)
library(tidymodels)
```
```{r}
data("bivariate")
```

```{r}
bivariate_train %>% 
  ggplot(aes(A, B, color = Class)) +
  geom_point(alpha = .3) +
  coord_equal(ratio = 20)
```

```{r}
bivariate_train %>% 
  pivot_longer(c(A, B), names_to = "predictor") %>% 
  ggplot(aes(x = Class, y = value)) +
  geom_boxplot() +
  facet_wrap(~predictor, scales = "free_y") +
  scale_y_log10()
```
```{r}
logit_mod <-
  logistic_reg() %>% 
  set_engine("glm")
```

```{r}
glm_workflow <-
  workflow() %>%
  add_model(logit_mod) %>% 
  add_formula(Class ~ .) %>% 
  fit(data = bivariate_train)
glm_workflow
```

```{r}
simple_glm_probs <-
  predict(glm_workflow, new_data = bivariate_val, type = "prob") %>% 
  bind_cols(bivariate_val)
simple_glm_probs
```
```{r}
simple_glm_roc <-
  simple_glm_probs %>% 
  roc_curve(Class, .pred_One)
simple_glm_roc
```
```{r}
simple_glm_roc %>% autoplot()
```

```{r}
ratio_glm <-
  glm_workflow %>% 
  update_formula(Class ~ I(A / B)) %>% 
  fit(data = bivariate_train)
ratio_glm
```

```{r}
ratio_glm_probs <-
  predict(ratio_glm, bivariate_val, type = "prob") %>% 
  bind_cols(bivariate_val)
ratio_glm_probs
```
```{r}
ratio_glm_roc <-
  ratio_glm_probs %>% 
  roc_curve(Class, .pred_One)
ratio_glm_roc
```
```{r}
ratio_glm_probs %>% roc_auc(Class, .pred_One)
```

```{r}
autoplot(simple_glm_roc) +
  geom_path(
    data = ratio_glm_roc,
    aes(x = 1 - specificity, y = sensitivity),
    color = "#FDE725FF"
  )
```

```{r}
trans_recipe <-
  recipe(Class ~ ., data = bivariate_train) %>% 
  step_BoxCox(all_predictors())
trans_recipe
```

```{r}
updated_rec <- prep(trans_recipe)
```


```{r}
trans_glm <- 
  glm_workflow %>% 
  update_recipe(trans_recipe) %>% 
  fit(data = bivariate_train)

trans_glm
```

```{r}
trans_glm_probs <-
  predict(trans_glm, bivariate_val, type = "prob") %>%
  bind_cols(bivariate_val)
```


```{r}
trans_glm_roc <- 
  trans_glm_probs %>% 
  roc_curve(Class, .pred_One)

trans_glm_probs %>% roc_auc(Class, .pred_One)
```

```{r}
autoplot(simple_glm_roc) + 
  geom_path(
    data = ratio_glm_roc, 
    aes(x = 1 - specificity, y = sensitivity), 
    col = "#FDE725FF"
  ) + 
  geom_path(
    data = trans_glm_roc, 
    aes(x = 1 - specificity, y = sensitivity), 
    col = "#21908CFF"
  )
```

```{r}
ggplot(bivariate_train, aes(x = 1/A, y = 1/B, col = Class)) + 
  geom_point(alpha = .3) + 
  coord_equal(ratio = 1/12)
```

```{r}
pca_recipe <- 
  trans_recipe %>% 
  step_normalize(A, B) %>%
  step_pca(A, B, num_comp = 2)

pca_glm <-
  glm_workflow %>%
  update_recipe(pca_recipe) %>% 
  fit(data = bivariate_train)

pca_glm_probs <-
  predict(pca_glm, bivariate_val, type = "prob") %>%
  bind_cols(bivariate_val)

pca_glm_roc <- 
  pca_glm_probs %>% 
  roc_curve(Class, .pred_One)

pca_glm_probs %>% roc_auc(Class, .pred_One)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.815
```


```{r}
library(discrim)

discrim_mod <- 
  discrim_flexible() %>%
  set_engine("earth") %>%
  set_mode("classification") 

discrim_wflow <- 
  workflow() %>% 
  add_recipe(trans_recipe) %>% 
  add_model(discrim_mod) %>% 
  fit(data = bivariate_train)

discrim_probs <-
  predict(discrim_wflow, bivariate_val, type = "prob") %>%
  bind_cols(bivariate_val)

discrim_roc <- 
  discrim_probs %>% 
  roc_curve(Class, .pred_One)

discrim_probs %>% roc_auc(Class, .pred_One)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.813
```

```{r}
ggplot(bivariate_train, aes(x = 1/A, y = 1/B, col = Class)) + 
  geom_point(alpha = .3) + 
  coord_equal(ratio = 1/12)
```

```{r}
test_probs <- 
  predict(trans_glm, bivariate_test, type = "prob") %>%
  bind_cols(bivariate_test)

test_roc <- 
  test_probs %>% 
  roc_curve(Class, .pred_One)

# A little more optimistic than the validation set
test_probs %>% roc_auc(Class, .pred_One)
#> # A tibble: 1 x 3
#>   .metric .estimator .estimate
#>   <chr>   <chr>          <dbl>
#> 1 roc_auc binary         0.862

autoplot(simple_glm_roc) 
```














